server:
  port: 8080
spring:
  application:
    name: wysiwyg-gateway
  profiles:
    active: @package.env@
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: wysiwyg-admin
          uri: http://localhost:8088
          predicates:
            - Path=/wysiwyg-admin/**
logging:
  file:
    path: /logs
#    org.springframework.web: TRACE
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.cloud.gateway: DEBUG

