#server:
#  port: 8088
#  servlet:
#    context-path: /wysiwyg
#spring:
#  profiles:
#    active: prod
#  # redis相关配置
#  redis:
#    host: 121.4.81.99
#    port: 6379
#    password: root
#  datasource:
#    username: root
#    password: wwcc
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://121.4.81.99:3306/wysiwyg?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#    druid:
#      #      aop-patterns: com.wysiwyg.admin.*  #监控SpringBean
#      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）
#      stat-view-servlet:   # 配置监控页功能
#        enabled: true
#        login-username: admin
#        login-password: admin
#        resetEnable: false
#      web-stat-filter:  # 监控web
#        enabled: true
#        urlPattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#      filter:
#        stat:    # 对上面filters里面的stat的详细配置
#          slow-sql-millis: 1000
#          logSlowSql: true
#          enabled: true
#        wall:
#          enabled: true
#          config:
#            drop-table-allow: false
#  resources:
#    static-locations: classpath:/static,classpath:/META-INF/resources
#  servlet:
#    multipart:
#      #      单个文件最大
#      max-file-size: 10MB
#      #      整个请求文件大小
#      max-request-size: 100MB
#  jackson:
#    serialization:
#      indent-output: true
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#
##mybatis配置
#mybatis:
#  #映射文件路径
#  mapper-locations: classpath:mapper/**/*.xml
#  #模型所在的包命
#  type-aliases-package: com.wysiwyg.admin.orm.entity
#  configuration:
#    map-underscore-to-camel-case: true #开启驼峰下划线转换
## jwt
#jwt:
#  config:
#    enabled: true
#    key-location: wysiwyg.jks
#    key-alias: wysiwyg
#    key-pass: 123456
#    iss: wysiwyg.com
#    sub: all
#    access-exp-days: 30
#    refresh-exp-days: 90
#management:
#  endpoint:
#    shutdown:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: *
#feign:
#  client:
#    config:
