server:
  port: 8088
  servlet:
    context-path: /wysiwyg-admin
spring:
  profiles:
    active: @package.env@

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #模型所在的包命
  type-aliases-package: com.wysiwyg.admin.model.po
  configuration:
    map-underscore-to-camel-case: true #开启驼峰下划线转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台日志输出
  inject-sql-session-on-mapper-scan: true
